config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  require "sidekiq/cron/web"

  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  use_doorkeeper

  mount MailPreview => "mail_view" if Rails.env.development?

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticate :user, ->(u) { u.director? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  # devise doesnt parse GET /user
  resource :user, only: :show, constraints: ->(req) { req.format == :json }

  resource :questionnaires, path: "apply" do
    get :schools, on: :collection
  end

  resource :rsvp do
    get :accept, on: :collection
    get :deny, on: :collection
  end

  resource :bus_list do
    patch :boarded_bus, on: :collection
  end

  resource :events, only: :show, constraints: ->(req) { req.format == :json }

  namespace :manage do
    authenticate :user, ->(u) { u.director? } do
      root to: "dashboard#index"
    end
    authenticate :user, ->(u) { u.organizer? } do
      root to: "dashboard#index", as: :organizer_root
    end
    authenticate :user, ->(u) { u.volunteer? } do
      root to: "checkins#index", as: :volunteer_root
    end
    resources :dashboard do
      get :map_data, on: :collection
      get :todays_activity_data, on: :collection
      get :todays_stats_data, on: :collection
      get :checkin_activity_data, on: :collection
      get :confirmation_activity_data, on: :collection
      get :application_activity_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :user_distribution_data, on: :collection
      get :application_distribution_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :schools_applied_data, on: :collection
    end
    resources :questionnaires do
      patch :check_in, on: :member
      patch :update_acc_status, on: :member
      patch :bulk_apply, on: :collection
    end
    resources :checkins do
      post :datatable, on: :collection
    end
    resources :events do
    end
    resources :messages do
      get :preview, on: :member
      get :live_preview, on: :collection
      patch :deliver, on: :member
      patch :duplicate, on: :member
      # Message template
      get :template, on: :collection
      get :template_preview, on: :collection
      patch :template_update, on: :collection
      post :template_replace_with_default, on: :collection
    end
    resources :bus_lists do
      post :toggle_bus_captain, on: :member
      patch :send_update_email, on: :member
    end
    resources :schools do
      post :datatable, on: :collection
      get :merge, on: :member
      patch :perform_merge, on: :member
    end
    resources :stats do
      post :checked_in_datatable, on: :collection
    end
    resources :users do
      patch :reset_password, on: :member
    end
    resources :agreements
    resources :configs do
      patch :update_only_css_variables, on: :member
      get :enter_theming_editor, on: :collection
      get :exit_theming_editor, on: :collection
    end
    resources :trackable_events
    resources :trackable_tags
    resources :data_exports
  end
end

app/controllers/questionnaires_controller.rb
class QuestionnairesController < ApplicationController
  include QuestionnairesControllable

  before_action :logged_in
  before_action :find_questionnaire, only: [:show, :update, :edit, :destroy]

  def logged_in
    authenticate_user!
  end

  # GET /apply
  # GET /apply.json
  def show
    flash[:alert] = nil
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @questionnaire }
    end
  end

  # GET /apply/new
  # GET /apply/new.json
  def new
    if current_user.questionnaire.present?
      return redirect_to questionnaires_path
    end
    @questionnaire = Questionnaire.new
    @agreements = Agreement.all

    if session["devise.provider_data"] && session["devise.provider_data"]["info"]
      info = session["devise.provider_data"]["info"]
      @skip_my_mlh_fields = true
      unless all_my_mlh_fields_provided?
        flash[:notice] = nil
        flash[:alert] = t(:my_mlh_null, scope: 'errors')
      end
      @questionnaire.tap do |q|
        q.phone          = info["phone_number"]
        q.level_of_study = info["level_of_study"]
        q.major          = info["major"]
        q.date_of_birth  = info["date_of_birth"]
        q.gender         = info["gender"]

        if info["school"]
          school = School.where(name: info["school"]["name"]).first_or_create do |s|
            s.name = info["school"]["name"]
          end
          q.school_id = school.id
        end
      end
    end

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @questionnaire }
    end
  end

  # GET /apply/edit
  def edit
    @agreements = Agreement.all
  end

  # POST /apply
  # POST /apply.json
  def create
    if current_user.reload.questionnaire.present?
      return redirect_to questionnaires_path, notice: 'Application already exists.'
    end
    return unless HackathonConfig.accepting_questionnaires

    @questionnaire = Questionnaire.new(convert_school_name_to_id(questionnaire_params))
    @questionnaire.user_id = current_user.id
    @agreements = Agreement.all

    respond_to do |format|
      if @questionnaire.save
        @questionnaire.update_attribute(:acc_status, default_acc_status)
        format.html { redirect_to questionnaires_path }
        format.json { render json: @questionnaire, status: :created, location: @questionnaire }
      else
        format.html { render action: "new" }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /apply
  # PUT /apply.json
  def update
    update_params = questionnaire_params
    update_params = convert_school_name_to_id(update_params)

    @agreements = Agreement.all
    respond_to do |format|
      if @questionnaire.update(update_params)
        format.html { redirect_to questionnaires_path, notice: 'Application was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @questionnaire.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /apply
  # DELETE /apply.json
  def destroy
    if @questionnaire.is_bus_captain
      directors = User.where(role: :director)
      directors.each do |user|
        StaffMailer.bus_captain_left(@questionnaire.bus_list_id, @questionnaire.user_id, user.id).deliver_later
      end
    end

    @questionnaire.destroy
    respond_to do |format|
      format.html { redirect_to questionnaires_url }
      format.json { head :no_content }
    end
  end

  # GET /apply/schools
  def schools
    if params[:name].blank? || params[:name].length < 3
      head :bad_request
      return
    end
    schools = School.where('name LIKE ?', "%#{params[:name]}%").order(questionnaire_count: :desc).limit(20).select(:name).all
    render json: schools.map(&:name)
  end

  private

  def all_my_mlh_fields_provided?
    info = session["devise.provider_data"]["info"]

    return true unless info["phone_number"].blank? || info["level_of_study"].blank? || info["major"].blank? ||
                       info["date_of_birth"].blank? || info["gender"].blank? || info["school"].blank? ||
                       info["school"]["name"].blank?
  end

  def questionnaire_params
    params.require(:questionnaire).permit(
      :email, :experience, :gender,
      :date_of_birth, :interest, :school_id, :school_name, :major, :level_of_study,
      :shirt_size, :dietary_restrictions, :special_needs, :international, :country,
      :portfolio_url, :vcs_url, :bus_captain_interest,
      :phone, :can_share_info, :travel_not_from_school, :travel_location,
      :graduation_year, :race_ethnicity, :resume, :delete_resume, :why_attend, agreement_ids: []
    )
  end

  def find_questionnaire
    unless current_user.questionnaire.present?
      return redirect_to new_questionnaires_path
    end
    @questionnaire = current_user.questionnaire
  end

  def default_acc_status
    return "late_waitlist" if HackathonConfig.auto_late_waitlist
    "pending"
  end
end

app/helpers/questionnaire_helper.rb
module QuestionnaireHelper
  def format_age(age)
    parts = ActiveSupport::Duration.build(age).parts

    "#{pluralize(parts[:years], 'year')}, #{pluralize(parts[:months], 'month')}, and #{pluralize(parts[:days], 'day')}"
  end
end

app/views/questionnaires/_form.html.haml
%div{class:"form-container wizard#{@skip_my_mlh_fields ? " wizard-skip-valid" : ""}"}
  = simple_form_for @questionnaire, url: url_for(controller: "questionnaires", action: "update"), html: { "data-validate" => "form" } do |f|

    - if f.error_notification.present?
      = f.error_notification

    .wizard-stage.wizard-current
      - if HackathonConfig.disclaimer_message.present?
        #disclaimer
          = markdown(HackathonConfig.disclaimer_message)

      .form-inputs
        = f.input :phone, label: "Phone number", input_html: { "data-validate" => ["presence", "phone"] }
        = f.input :date_of_birth, start_year: Date.today.year - 5, end_year: Date.today.year - 90, order: [:month, :day, :year], input_html: { "data-validate" => "presence" }

        = f.input :school_id, as: :school_selection, input_html: { "data-validate" => "presence" }
        = f.input :level_of_study, collection: collection_or_text(@questionnaire.level_of_study, Questionnaire::POSSIBLE_LEVELS_OF_STUDY), include_blank: "(select one...)", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
        = f.input :major, input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
        = f.input :gender, collection: collection_or_text(@questionnaire.gender, Questionnaire::POSSIBLE_GENDERS), include_blank: "(select one...)", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
      .right
        %button.button{ type: "button", "data-wizard" => "next" } Next

    .wizard-stage
      .form-inputs
        - if HackathonManager.field_enabled?(:why_attend)
          = f.input :why_attend, label: "Why #{HackathonConfig.hackathon_name}?", placeholder: "In a sentence or two, why would you like to attend #{HackathonConfig.hackathon_name}?", input_html: { rows: 3, maxlength: 280 }

        = f.input :experience, as: :select, collection: Questionnaire::POSSIBLE_EXPERIENCES.invert, include_blank: "(select one...)", label: "Experience", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
        = f.input :interest, as: :select, collection: Questionnaire::POSSIBLE_INTERESTS.invert, include_blank: "(select one...)", label: "Interest", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }

        = f.input :graduation_year, as: :select, collection: Questionnaire::POSSIBLE_GRAD_YEARS, include_blank: "(select one...)", label: "Graduation year", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
        = f.input :race_ethnicity, as: :select, collection: Questionnaire::POSSIBLE_RACE_ETHNICITIES, include_blank: "(select one...)", label: "Race/Ethnicity", input_html: { "data-validate" => "presence" }, wrapper_html: { class: 'input--half' }
        = f.input :country, as: :select, collection: Questionnaire::POSSIBLE_COUNTRIES, include_blank: "(select one...)", input_html: { "data-validate" => "presence" }

        = f.input :portfolio_url, label: "Portfolio link", placeholder: "http://mywebsite.com"
        = f.input :vcs_url, label: "GitHub/GitLab/Bitbucket link", placeholder: "https://github.com/coderit"
        = f.input :resume, as: :deletable_attachment, hint: "Must be a PDF, under 2MB", input_html: { "data-validate" => "file-max-size file-content-type", "data-validate-file-max-size" => "2097152", "data-validate-file-content-type" => "application/pdf" }, label: "Resume"
        = f.input :can_share_info, as: :radio_buttons, collection: { " Yes please!" => true, " No, thank you." => false }, label: "Share info with sponsors?", hint: "Our sponsors would receive info such as your name, email, resume, GitHub link, etc"

        - if !HackathonConfig.digital_hackathon
          - travel_state = !@questionnaire.new_record? && @questionnaire.travel_not_from_school
          = f.input :travel_not_from_school, as: :radio_buttons, collection: { " My school" => false, " Somewhere else" => true }, label: "I am traveling from..."
          = f.input :travel_location, input_html: { "data-validate" => "presence", disabled: !travel_state }, wrapper_html: { style: travel_state ? "" : "display: none" }, label: "Where are you traveling from?", placeholder: "New York City"

        = f.input :shirt_size, as: :select, collection: Questionnaire::POSSIBLE_SHIRT_SIZES, include_blank: "(select one...)", input_html: { "data-validate" => "presence" }

        - if !HackathonConfig.digital_hackathon
          = f.input :dietary_restrictions, as: :text, label: "Dietary restrictions", wrapper_html: { class: 'input--half' }, maxlength: Questionnaire::DIETARY_SPECIAL_NEEDS_MAX_LENGTH
        = f.input :special_needs, as: :text, label: "Special needs", wrapper_html: { class: 'input--half' }, maxlength: Questionnaire::DIETARY_SPECIAL_NEEDS_MAX_LENGTH

      - if @agreements.any?
        %hr
        %strong Agreements
        %p Please review the agreements and click the corresponding checkbox next to each agreement to agree.
        .form-inputs
          = f.association :agreements, as: :check_boxes, label_method: :formatted_agreement, value_method: :id, label: "", wrapper_html: { style: 'display: block' }, input_html: { "data-validate" => "presence", class: "agreement_input"}

      .right
        %button.button{ type: "button", "data-wizard" => "previous" } Previous
        &nbsp;
        = f.button :submit, value: ( @questionnaire.new_record? ? 'Apply' : 'Save' )

app/views/questionnaires/new.html.haml
- title "Application"
- if HackathonConfig.accepting_questionnaires
  .form-container
    %h1.section-title
      Apply for
      %span.emphasized= HackathonConfig.hackathon_name
  = render 'form'
- else
  .form-container
    #disclaimer
      %h1.section-title
        Applications Closed
      %p
        - if HackathonConfig.questionnaires_closed_message.present?
          = markdown(HackathonConfig.questionnaires_closed_message)
        - else
          Sorry, we are no longer accepting new applications to
          %strong
            #{HackathonConfig.hackathon_name}.
          %br
    %p.session-link.right
      Don't need your account? #{link_to "Delete my account", user_registration_path, data: { confirm: "Are you sure? Your account and any related data will be permanently erased." }, method: :delete}

app/views/questionnaires/show.html.haml
- title "Application"
.form-container
  - if @questionnaire.unaccepted_agreements.any?
    = render partial: 'unaccepted_agreements_notice'
  - if @questionnaire.country.blank?
    = render partial: 'missing_country_notice'
.form-container
  #disclaimer
    %h1.section-title
      Application
      %span.emphasized Status
    - if @questionnaire.blank?
      %p
        %strong AWAITING APPLICATION
    - else
      %p
        %strong= @questionnaire.verbal_status.upcase
      - if @questionnaire.can_rsvp?
        - if @questionnaire.did_rsvp?
          - if @questionnaire.acc_status == "rsvp_confirmed"
            %p
              Congratulations! You're all set to attend #{HackathonConfig.hackathon_name}!
          - if HackathonConfig.thanks_for_rsvp_message.present?
            = markdown(HackathonConfig.thanks_for_rsvp_message)
          %p.center
            = btn_link_to "Change RSVP", rsvp_path
        - else
          %p
            Please RSVP so we know if you're attending!
            %br
            %br
          %p.center
            = btn_link_to "RSVP NOW &raquo;".html_safe, rsvp_path
      - if !@questionnaire.can_rsvp? && @questionnaire.acc_status != "denied"
        - if HackathonConfig.accepting_questionnaires
          - if HackathonConfig.thanks_for_applying_message.present?
            = markdown(HackathonConfig.thanks_for_applying_message)
          - else
            %p Thanks for applying! You will be notified of your acceptance via email.
        - else
          %p Thanks for applying!

.form-container
  %h1.section-title.section-title--actions
    %span
      Review your
      %span.emphasized Application
    = btn_link_to 'Edit', edit_questionnaires_path, class: 'section-title__action'

  .participant_info
    = render partial: 'questionnaire_summary'

  %br
  %p.session-link.right
    Unhappy? #{link_to "Revoke my application", user_registration_path, data: { confirm: "Are you sure? Your account and application will be permanently erased." }, method: :delete}