config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  require "sidekiq/cron/web"

  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  use_doorkeeper

  mount MailPreview => "mail_view" if Rails.env.development?

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticate :user, ->(u) { u.director? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  # devise doesnt parse GET /user
  resource :user, only: :show, constraints: ->(req) { req.format == :json }

  resource :questionnaires, path: "apply" do
    get :schools, on: :collection
  end

  resource :rsvp do
    get :accept, on: :collection
    get :deny, on: :collection
  end

  resource :bus_list do
    patch :boarded_bus, on: :collection
  end

  resource :events, only: :show, constraints: ->(req) { req.format == :json }

  namespace :manage do
    authenticate :user, ->(u) { u.director? } do
      root to: "dashboard#index"
    end
    authenticate :user, ->(u) { u.organizer? } do
      root to: "dashboard#index", as: :organizer_root
    end
    authenticate :user, ->(u) { u.volunteer? } do
      root to: "checkins#index", as: :volunteer_root
    end
    resources :dashboard do
      get :map_data, on: :collection
      get :todays_activity_data, on: :collection
      get :todays_stats_data, on: :collection
      get :checkin_activity_data, on: :collection
      get :confirmation_activity_data, on: :collection
      get :application_activity_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :user_distribution_data, on: :collection
      get :application_distribution_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :schools_applied_data, on: :collection
    end
    resources :questionnaires do
      patch :check_in, on: :member
      patch :update_acc_status, on: :member
      patch :bulk_apply, on: :collection
    end
    resources :checkins do
      post :datatable, on: :collection
    end
    resources :events do
    end
    resources :messages do
      get :preview, on: :member
      get :live_preview, on: :collection
      patch :deliver, on: :member
      patch :duplicate, on: :member
      # Message template
      get :template, on: :collection
      get :template_preview, on: :collection
      patch :template_update, on: :collection
      post :template_replace_with_default, on: :collection
    end
    resources :bus_lists do
      post :toggle_bus_captain, on: :member
      patch :send_update_email, on: :member
    end
    resources :schools do
      post :datatable, on: :collection
      get :merge, on: :member
      patch :perform_merge, on: :member
    end
    resources :stats do
      post :checked_in_datatable, on: :collection
    end
    resources :users do
      patch :reset_password, on: :member
    end
    resources :agreements
    resources :configs do
      patch :update_only_css_variables, on: :member
      get :enter_theming_editor, on: :collection
      get :exit_theming_editor, on: :collection
    end
    resources :trackable_events
    resources :trackable_tags
    resources :data_exports
  end
end

app/models/bus_list.rb
class BusList < ApplicationRecord
  include PgSearch::Model
  pg_search_scope :search, against: [:name], using: { tsearch: { prefix: true } }
  audited

  validates_presence_of :name, :capacity
  validates_uniqueness_of :name, case_sensitive: false

  has_many :questionnaires

  strip_attributes

  def self.ransackable_attributes(_)
    ["created_at", "id", "name", "updated_at"]
  end

  def full?
    passengers.count >= capacity
  end

  def passengers
    questionnaires.where("acc_status = 'rsvp_confirmed'")
  end

  def schools
    passengers.joins(:school).map(&:school).uniq
  end

  def checked_in_passengers
    passengers.select(&:checked_in?)
  end

  def boarded_passengers
    passengers.select(&:boarded_bus?)
  end

  def captains
    passengers.where(is_bus_captain: true)
  end

  def name_maybe_full
    full? ? "(full) #{name}" : name
  end
end

app/controllers/bus_lists_controller.rb
class BusListsController < ApplicationController
  before_action :check_user_has_questionnaire
  before_action :find_questionnaire
  before_action :find_bus_list
  before_action :require_bus_captain

  # GET /bus_list
  def show
  end

  # PATCH /bus_list/boarded_bus
  def boarded_bus
    boarded_bus = params[:questionnaire][:boarded_bus].to_s
    questionnaire = Questionnaire.find_by_id(params[:questionnaire][:id])

    if !['true', 'false'].include?(boarded_bus) || questionnaire.blank?
      head :bad_request
      return
    end

    if questionnaire.bus_list.id != @bus_list.id
      head :bad_request
      return
    end

    if boarded_bus == 'true'
      questionnaire.update_attribute(:boarded_bus_at, Time.now)
    else
      questionnaire.update_attribute(:boarded_bus_at, nil)
    end
    head :ok
  end

  private

  def find_questionnaire
    @questionnaire = current_user.questionnaire
    return head :not_found, notice: 'Questionnaire does not exist.' unless @questionnaire
  end

  def find_bus_list
    @bus_list = @questionnaire.bus_list
    return head :not_found, notice: 'Bus List does not exist.' unless @bus_list
  end

  def check_user_has_questionnaire
    if current_user.questionnaire.nil?
      head :not_found, notice: 'Questionnaire does not exist.'
    end
  end

  def require_bus_captain
    return head :unauthorized unless @questionnaire.is_bus_captain?
  end
end

app/views/bus_lists/show.html.haml
- title "Bus Captain"
.form-container.participant_info
  %h1.section-title
    Bus
    %span.emphasized Captain

  %p Thank you for being a bus captain! Below is any information you may need about your passengers.

  %p Please note that your contact information as shown below is shared with passengers, should they need to contact you.

  %p
    If a student was accepted but didn't RSVP or sign up for the bus, they can go to
    %strong= rsvp_url
    to do so.

  - if HackathonConfig.bus_captain_notes.present?
    = markdown(HackathonConfig.bus_captain_notes)

  %p
    %b Bus List Name:
    = @bus_list.name

  = render partial: 'bus_list_info', locals: { bus_list: @bus_list }

  %p
    %strong Passengers:
    (#{@bus_list.passengers.count} total,
    <span id="boarded-bus-count">#{@bus_list.boarded_passengers.count} boarded</span>,
    #{@bus_list.checked_in_passengers.count} checked in)

  %table.table
    %thead
      %tr
        %th Boarded bus?
        %th First Name
        %th Last Name
        %th Email
        %th Phone Number
        %th School
        %th Checked in?
    %tbody
      - @bus_list.passengers.each do |p|
        %tr
          %td
            %input{type: 'checkbox', checked: p.boarded_bus?, data: { "boarded-bus": true, action: boarded_bus_bus_list_path, id: p.id } }
          %td= p.user.first_name
          %td= p.user.last_name
          %td= p.email
          %td= phone_link_to p.phone
          %td= p.school.name
          %td= p.checked_in? ? '<span class="acc-status-accepted">Yes</span>'.html_safe : 'No'

  = render partial: 'bus_list_stats', locals: { bus_list: @bus_list }