config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  require "sidekiq/cron/web"

  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  use_doorkeeper

  mount MailPreview => "mail_view" if Rails.env.development?

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticate :user, ->(u) { u.director? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  # devise doesnt parse GET /user
  resource :user, only: :show, constraints: ->(req) { req.format == :json }

  resource :questionnaires, path: "apply" do
    get :schools, on: :collection
  end

  resource :rsvp do
    get :accept, on: :collection
    get :deny, on: :collection
  end

  resource :bus_list do
    patch :boarded_bus, on: :collection
  end

  resource :events, only: :show, constraints: ->(req) { req.format == :json }

  namespace :manage do
    authenticate :user, ->(u) { u.director? } do
      root to: "dashboard#index"
    end
    authenticate :user, ->(u) { u.organizer? } do
      root to: "dashboard#index", as: :organizer_root
    end
    authenticate :user, ->(u) { u.volunteer? } do
      root to: "checkins#index", as: :volunteer_root
    end
    resources :dashboard do
      get :map_data, on: :collection
      get :todays_activity_data, on: :collection
      get :todays_stats_data, on: :collection
      get :checkin_activity_data, on: :collection
      get :confirmation_activity_data, on: :collection
      get :application_activity_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :user_distribution_data, on: :collection
      get :application_distribution_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :schools_applied_data, on: :collection
    end
    resources :questionnaires do
      patch :check_in, on: :member
      patch :update_acc_status, on: :member
      patch :bulk_apply, on: :collection
    end
    resources :checkins do
      post :datatable, on: :collection
    end
    resources :events do
    end
    resources :messages do
      get :preview, on: :member
      get :live_preview, on: :collection
      patch :deliver, on: :member
      patch :duplicate, on: :member
      # Message template
      get :template, on: :collection
      get :template_preview, on: :collection
      patch :template_update, on: :collection
      post :template_replace_with_default, on: :collection
    end
    resources :bus_lists do
      post :toggle_bus_captain, on: :member
      patch :send_update_email, on: :member
    end
    resources :schools do
      post :datatable, on: :collection
      get :merge, on: :member
      patch :perform_merge, on: :member
    end
    resources :stats do
      post :checked_in_datatable, on: :collection
    end
    resources :users do
      patch :reset_password, on: :member
    end
    resources :agreements
    resources :configs do
      patch :update_only_css_variables, on: :member
      get :enter_theming_editor, on: :collection
      get :exit_theming_editor, on: :collection
    end
    resources :trackable_events
    resources :trackable_tags
    resources :data_exports
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include Pagy::Backend
  protect_from_forgery with: :exception

  def after_sign_in_path_for(resource)
    stored_location = stored_location_for(resource)
    if stored_location
      stored_location
    elsif current_user.staff?
      manage_root_path
    elsif current_user.questionnaire.nil?
      new_questionnaires_path
    else
      questionnaires_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/views/application/_bus_list_info.html.erb
<fieldset>
  <legend>Bus Captains</legend>
  <% if bus_list.captains.empty? %>
    <p>
      <em>TBD</em>
    </p>
  <% end %>
  <% bus_list.captains.each do |p| %>
    <p>
      <strong>
        <%= p.user.full_name %>
      </strong>
      <br/>
      <em>
        <%= p.school.name %>
      </em>
      <br/>
      Phone:
      <%= p.phone %>
      <br/>
      Email:
      <%= p.email %>
    </p>
  <% end %>
</fieldset>
<fieldset>
  <legend>Bus Notes</legend>
  <%= bus_list.notes.present? ? markdown(bus_list.notes.html_safe) : "<p>(none)</p>".html_safe %>
</fieldset>

app/views/application/_bus_list_stats.html.erb
<% passengers = Questionnaire.joins(:school).group('schools.name').where(acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).order("schools.name ASC").count %>
<%= pie_chart passengers %>
<br/>
<ruby>
  
  school_ids = Questionnaire.where(acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).distinct.pluck(:school_id)
  schools = Questionnaire.joins(:school).group('schools.name').where(school_id: school_ids, acc_status: 'rsvp_confirmed').order("schools.name ASC").count
  schools_riding = Questionnaire.joins(:school).group('schools.name').where(school_id: school_ids, acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).count
  schools = schools.map do |name, count|
    bus_count_row = schools_riding.select { |school_bus_name, _| school_bus_name == name }
    bus_count = bus_count_row ? bus_count_row[name] || 0 : 0
    count_without_bus = count - bus_count
    [name, count_without_bus, bus_count]
  end
  data = [
    { name: "Attending but not riding this bus", data: schools.sort_by { |_, no_bus, bus| [bus, no_bus] }.reverse },
    { name: "Riding this bus", data: schools_riding }
  ]

</ruby>
<%= bar_chart data, stacked: true, height: '400px' %>

app/views/application/_bus_list_stats.html.haml
- passengers = Questionnaire.joins(:school).group('schools.name').where(acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).order("schools.name ASC").count
= pie_chart passengers

%br

:ruby
  school_ids = Questionnaire.where(acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).distinct.pluck(:school_id)
  schools = Questionnaire.joins(:school).group('schools.name').where(school_id: school_ids, acc_status: 'rsvp_confirmed').order("schools.name ASC").count
  schools_riding = Questionnaire.joins(:school).group('schools.name').where(school_id: school_ids, acc_status: 'rsvp_confirmed', bus_list_id: @bus_list.id).count
  schools = schools.map do |name, count|
    bus_count_row = schools_riding.select { |school_bus_name, _| school_bus_name == name }
    bus_count = bus_count_row ? bus_count_row[name] || 0 : 0
    count_without_bus = count - bus_count
    [name, count_without_bus, bus_count]
  end
  data = [
    { name: "Attending but not riding this bus", data: schools.sort_by { |_, no_bus, bus| [bus, no_bus] }.reverse },
    { name: "Riding this bus", data: schools_riding }
  ]
= bar_chart data, stacked: true, height: '400px'

app/views/application/_missing_country_notice.html.haml
.alert#disclaimer
  %h1.section-title
    %span.emphasized.fa.fa-exclamation-circle
    Missing
    %span.emphasized Country Information
  %p
    You have not provided the country you are hacking from. Please
    %strong
      #{link_to "edit your application", edit_questionnaires_path}
    and specify your country.

app/views/application/_my_mlh_cta.html.erb
<%= link_to user_mlh_omniauth_authorize_path, class: 'button my-mlh-cta__button', method: :post do %>
  <span class="my-mlh-cta__text">Continue with</span>
  <span class="my-mlh-cta__image-wrapper">
    <%= image_tag 'my-mlh.svg', alt: 'My MLH', class: 'my-mlh-cta__image' %>
    <span class="fa fa-chevron-right my-mlh-cta__icon"></span>
  </span>
<% end %>

app/views/application/_questionnaire_summary.html.erb
<% if HackathonManager.field_enabled?(:why_attend) %>
  <p>
    <b>Why #{HackathonConfig['name']}?</b>
  </p>
  <p>
    <%= @questionnaire.why_attend.presence || "(not provided)" %>
  </p>
<% end %>
<p>
  <b>Experience:</b>
  <%= Questionnaire::POSSIBLE_EXPERIENCES[@questionnaire.experience] %>
</p>
<p>
  <b>Portfolio link:</b>
  <%= @questionnaire.portfolio_url? ? link_to(@questionnaire.portfolio_url, @questionnaire.portfolio_url, target: '_blank', rel: 'noopener') : 'Not provided' %>
</p>
<p>
  <b>GitHub/GitLab/Bitbucket link:</b>
  <%= @questionnaire.vcs_url? ? link_to(@questionnaire.vcs_url, @questionnaire.vcs_url, target: '_blank', rel: 'noopener') : 'Not provided' %>
</p>
<p>
  <b>Resume:</b>
  <%= @questionnaire.resume.attached? ? link_to("Download &raquo;".html_safe, @questionnaire.resume) : 'Not provided' %>
</p>
<% if !HackathonConfig['digital_hackathon'] %>
  <p>
    <b>Traveling from:</b>
    <%= @questionnaire.travel_not_from_school ? "Somewhere else (#{@questionnaire.travel_location})" : "My school (#{@questionnaire.school.full_name})" %>
  </p>
<% end %>
<p>
  <b>Shirt size:</b>
  <%= @questionnaire.shirt_size %>
</p>
<% if !HackathonConfig['digital_hackathon'] %>
  <p>
    <b>Dietary restrictions</b>
    <%= @questionnaire.dietary_restrictions || "<i>(none)</i>".html_safe %>
  </p>
<% end %>
<p>
  <b>Special needs</b>
  <%= @questionnaire.special_needs || "<i>(none)</i>".html_safe %>
</p>
<fieldset>
  <% if @questionnaire.user.provider == 'mlh' %>
    <legend>Provided by MyMLH</legend>
  <% end %>
  <p>
    <b>First name:</b>
    <%= @questionnaire.user.first_name %>
  </p>
  <p>
    <b>Last name:</b>
    <%= @questionnaire.user.last_name %>
  </p>
  <p>
    <b>Email:</b>
    <%= @questionnaire.email %>
  </p>
  <p>
    <b>Phone:</b>
    <%= @questionnaire.phone %>
  </p>
  <p>
    <b>Date of birth:</b>
    <%= @questionnaire.date_of_birth_formatted %>
  </p>
  <p>
    <b>Gender:</b>
    <%= @questionnaire.gender %>
  </p>
  <p>
    <b>School:</b>
    <%= @questionnaire.school.full_name %>
  </p>
  <p>
    <b>Major:</b>
    <%= @questionnaire.major %>
  </p>
  <p>
    <b>Level of study:</b>
    <%= @questionnaire.level_of_study %>
  </p>
</fieldset>

app/views/application/_questionnaire_summary.html.haml
- if HackathonManager.field_enabled?(:why_attend)
  %p
    %b Why #{HackathonConfig.hackathon_name}?
  %p= @questionnaire.why_attend.presence || "(not provided)"
%p
  %b Experience:
  = Questionnaire::POSSIBLE_EXPERIENCES[@questionnaire.experience]
%p
  %b Portfolio link:
  = @questionnaire.portfolio_url? ? link_to(@questionnaire.portfolio_url, @questionnaire.portfolio_url, target: '_blank', rel: 'noopener') : 'Not provided'
%p
  %b GitHub/GitLab/Bitbucket link:
  = @questionnaire.vcs_url? ? link_to(@questionnaire.vcs_url, @questionnaire.vcs_url, target: '_blank', rel: 'noopener') : 'Not provided'
%p
  %b Resume:
  = @questionnaire.resume.attached? ? link_to("Download &raquo;".html_safe, @questionnaire.resume) : 'Not provided'
- if !HackathonConfig.digital_hackathon
  %p
    %b Traveling from:
    = @questionnaire.travel_not_from_school ? "Somewhere else (#{@questionnaire.travel_location})" : "My school (#{@questionnaire.school.full_name})"
%p
  %b Shirt size:
  = @questionnaire.shirt_size
- if !HackathonConfig.digital_hackathon
  %p
    %b Dietary restrictions
    = @questionnaire.dietary_restrictions || "<i>(none)</i>".html_safe
%p
  %b Special needs
  = @questionnaire.special_needs || "<i>(none)</i>".html_safe

%fieldset
  - if @questionnaire.user.provider == 'mlh'
    %legend Provided by MyMLH
  %p
    %b First name:
    = @questionnaire.user.first_name
  %p
    %b Last name:
    = @questionnaire.user.last_name
  %p
    %b Email:
    = @questionnaire.email
  %p
    %b Phone:
    = @questionnaire.phone
  %p
    %b Date of birth:
    = @questionnaire.date_of_birth_formatted
  %p
    %b Gender:
    = @questionnaire.gender
  %p
    %b School:
    = @questionnaire.school.full_name
  %p
    %b Major:
    = @questionnaire.major
  %p
    %b Level of study:
    = @questionnaire.level_of_study

app/views/application/_triggered_email_summary.html.erb
<h3 class="pb-2" id="triggered-email-overview">Automated Messages</h3>
<table class="table table-striped">
  <caption>
    <ul>
      <li class="mb-1">
        Recipient updates that match a given event will be sent the corresponding email(s) automatically.
        <br/>
        For example, when a user moves from the "Accepted" to "RSVP Confirmed" state, the user will be sent an email for the "RSVP Confirmed" event.
      </li>
      <li>Hard-coded emails are those managed in the source code repository, and cannot be disabled.</li>
    </ul>
  </caption>
  <thead>
    <tr>
      <th>Automation Event</th>
      <th>Message(s)</th>
    </tr>
  </thead>
  <tbody>
    <% Message::POSSIBLE_TRIGGERS.keys.each do |trigger| %>
      <tr>
        <td>
          <%= Message::POSSIBLE_TRIGGERS[trigger] %>
        </td>
        <% messages = Message.automated.where(trigger: trigger).all %>
        <td>
          <% if messages.present? %>
            <ul class="list-unstyled mb-0">
              <% messages.each do |message| %>
                <li>
                  <strong>
                    <%= link_to(message.name, manage_message_path(message)) %>
                  </strong>
                </li>
              <% end %>
            </ul>
          <% else %>
            None
          <% end %>
        </td>
      </tr>
    <% end %>
    <tr>
      <td>Disabled</td>
      <td>
        <% messages = Message.automated.where(trigger: nil).all %>
        <% if messages.present? %>
          <ul class="list-unstyled mb-0">
            <% messages.each do |message| %>
              <li>
                <strong>
                  <%= link_to(message.name, manage_message_path(message)) %>
                </strong>
              </li>
            <% end %>
          </ul>
        <% else %>
          None
        <% end %>
      </td>
    </tr>
  </tbody>
</table>

app/views/application/_unaccepted_agreements_notice.html.haml
.alert#disclaimer
  %h1.section-title
    %span.emphasized.fa.fa-exclamation-circle
    Missing
    %span.emphasized Agreements
  %p
    You have unaccepted agreements. You will not be allowed at #{HackathonConfig.hackathon_name} until all agreements have been accepted. Please
    %strong
      #{link_to "edit your application", edit_questionnaires_path}
    and review all agreements before attending.