config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  require "sidekiq/web"
  require "sidekiq/cron/web"

  devise_for :users, controllers: { registrations: "users/registrations", omniauth_callbacks: "users/omniauth_callbacks" }
  use_doorkeeper

  mount MailPreview => "mail_view" if Rails.env.development?

  devise_scope :user do
    root to: "devise/sessions#new"
  end

  authenticate :user, ->(u) { u.director? } do
    mount Sidekiq::Web => "/sidekiq"
    mount Blazer::Engine, at: "blazer"
  end

  # devise doesnt parse GET /user
  resource :user, only: :show, constraints: ->(req) { req.format == :json }

  resource :questionnaires, path: "apply" do
    get :schools, on: :collection
  end

  resource :rsvp do
    get :accept, on: :collection
    get :deny, on: :collection
  end

  resource :bus_list do
    patch :boarded_bus, on: :collection
  end

  resource :events, only: :show, constraints: ->(req) { req.format == :json }

  namespace :manage do
    authenticate :user, ->(u) { u.director? } do
      root to: "dashboard#index"
    end
    authenticate :user, ->(u) { u.organizer? } do
      root to: "dashboard#index", as: :organizer_root
    end
    authenticate :user, ->(u) { u.volunteer? } do
      root to: "checkins#index", as: :volunteer_root
    end
    resources :dashboard do
      get :map_data, on: :collection
      get :todays_activity_data, on: :collection
      get :todays_stats_data, on: :collection
      get :checkin_activity_data, on: :collection
      get :confirmation_activity_data, on: :collection
      get :application_activity_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :user_distribution_data, on: :collection
      get :application_distribution_data, on: :collection
      get :schools_confirmed_data, on: :collection
      get :schools_applied_data, on: :collection
    end
    resources :questionnaires do
      patch :check_in, on: :member
      patch :update_acc_status, on: :member
      patch :bulk_apply, on: :collection
    end
    resources :checkins do
      post :datatable, on: :collection
    end
    resources :events do
    end
    resources :messages do
      get :preview, on: :member
      get :live_preview, on: :collection
      patch :deliver, on: :member
      patch :duplicate, on: :member
      # Message template
      get :template, on: :collection
      get :template_preview, on: :collection
      patch :template_update, on: :collection
      post :template_replace_with_default, on: :collection
    end
    resources :bus_lists do
      post :toggle_bus_captain, on: :member
      patch :send_update_email, on: :member
    end
    resources :schools do
      post :datatable, on: :collection
      get :merge, on: :member
      patch :perform_merge, on: :member
    end
    resources :stats do
      post :checked_in_datatable, on: :collection
    end
    resources :users do
      patch :reset_password, on: :member
    end
    resources :agreements
    resources :configs do
      patch :update_only_css_variables, on: :member
      get :enter_theming_editor, on: :collection
      get :exit_theming_editor, on: :collection
    end
    resources :trackable_events
    resources :trackable_tags
    resources :data_exports
  end
end

app/views/layouts/_account_nav.html.erb
<% if current_user.present? %>
  <div class="account-nav">
    <div class="account-nav__wrapper">
      <div class="account-nav__links">
        <%= active_link_to 'Account', edit_user_registration_path, class: 'account-nav__link', active_class: 'account-nav__link--active' %>
        <% if current_user.questionnaire.present? && current_user.questionnaire.can_rsvp? %>
          <%= active_link_to 'RSVP', rsvp_path, class: 'account-nav__link', active_class: 'account-nav__link--active' %>
        <% end %>
        <%= active_link_to 'Application', questionnaires_path, class: 'account-nav__link', active_class: 'account-nav__link--active' %>
        <% if current_user.questionnaire.present? && current_user.questionnaire.bus_list_id && current_user.questionnaire.is_bus_captain? %>
          <%= active_link_to 'Bus Captain'.html_safe, bus_list_path, class: 'account-nav__link', active_class: 'account-nav__link--active' %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_flashes.html.erb
<% if flash[:alert].present? %>
  <div class="flashes flashes--error">
    <div class="container">
      <div class="form-container">
        <span class="fa fa-info-circle flashes__icon"></span>
        <%= flash[:alert].html_safe %>
      </div>
    </div>
  </div>
<% end %>
<% if flash[:notice].present? %>
  <div class="flashes">
    <div class="container">
      <div class="form-container">
        <span class="fa fa-info-circle flashes__icon"></span>
        <%= flash[:notice].html_safe %>
      </div>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<% homepage_url = HackathonConfig['homepage_url'].presence || root_path %>
<div class="header">
  <div class="header__wrapper account-nav__wrapper">
    <% if HackathonConfig['logo_asset'].present? %>
      <div class="header-logo">
        <%= link_to homepage_url do %>
          <%= image_tag HackathonConfig['logo_asset'], id: 'logo', alt: "#{HackathonConfig['name']} logo", title: HackathonConfig['name'], class: 'header-logo__image' %>
        <% end %>
      </div>
    <% else %>
      <div class="header-nav start">
        <%= btn_link_to "Home", homepage_url %>
      </div>
    <% end %>
    <div class="header-nav end">
      <% if user_signed_in? %>
        <% if current_user.organizing_staff? %>
          <%= btn_link_to "Manage", manage_root_path %>
        <% elsif current_user.volunteer? %>
          <%= btn_link_to "Manage", manage_checkins_path %>
        <% end %>
        <%= btn_link_to "Sign Out", destroy_user_session_path, method: :delete %>
      <% end %>
    </div>
  </div>
</div>

app/views/layouts/_header.html.haml
- homepage_url = HackathonConfig.homepage_url.presence || root_path
.header
  .header__wrapper.account-nav__wrapper
    - if HackathonConfig.logo_asset.present?
      .header-logo
        = link_to homepage_url do
          = image_tag HackathonConfig.logo_asset, id: 'logo', alt: "#{HackathonConfig.hackathon_name} logo", title: HackathonConfig.hackathon_name, class: 'header-logo__image'
    - else
      .header-nav.start
        = btn_link_to "Home", homepage_url
    .header-nav.end
      - if user_signed_in?
        - if current_user.staff?
          = btn_link_to "Manage", manage_root_path
        = btn_link_to "Sign Out", destroy_user_session_path, method: :delete

app/views/layouts/_theming_editor.html.erb
<div class="theming-editor__wrapper" id="theming-editor">
  <div class="theming-editor__title">Custom CSS Variables</div>
  <div class="theming-editor__variables">
    <div class="theming-editor__variable">
      <small class="theming-editor__variable-name">
        <code class="theming-editor__variable-name-code">my-variable</code>
      </small>
      <div class="theming-editor__input-group">
        <input class="theming-editor__input" type="text"></input>
        <div class="theming-editor__color-picker"></div>
      </div>
    </div>
  </div>
  <div class="theming-editor__button-wrapper">
    <button class="theming-editor__button-save" type="button">Save</button>
    <%= link_to 'Cancel', exit_theming_editor_manage_configs_path %>
  </div>
</div>
<%= javascript_include_tag "theming-editor/theming-editor.js", "data-turbolinks-eval": "false" %>

app/views/layouts/_theming_editor.html.haml
.theming-editor__wrapper#theming-editor
  .theming-editor__title Custom CSS Variables
  .theming-editor__variables
    .theming-editor__variable
      %small.theming-editor__variable-name
        %code.theming-editor__variable-name-code my-variable
      .theming-editor__input-group
        %input.theming-editor__input{type: 'text'}
        .theming-editor__color-picker

  .theming-editor__button-wrapper
    %button.theming-editor__button-save{type: 'button'} Save
    = link_to 'Cancel', exit_theming_editor_manage_configs_path

= javascript_include_tag "theming-editor/theming-editor.js", "data-turbo-eval": "false"

app/views/layouts/admin_mailer.html.erb
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml" xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office">
<head>
    <meta charset="utf-8"> <!-- utf-8 works for most cases -->
    <meta name="viewport" content="width=device-width"> <!-- Forcing initial-scale shouldn't be necessary -->
    <meta http-equiv="X-UA-Compatible" content="IE=edge"> <!-- Use the latest (edge) version of IE rendering engine -->
    <meta name="x-apple-disable-message-reformatting">  <!-- Disable auto-scale in iOS 10 Mail entirely -->
    <meta name="format-detection" content="telephone=no,address=no,email=no,date=no,url=no"> <!-- Tell iOS not to automatically link certain text strings. -->
    <title></title> <!-- The title tag shows in email notifications, like Android 4.4. -->

    <!-- CSS Reset : BEGIN -->
    <style>

        /* What it does: Remove spaces around the email design added by some email clients. */
        /* Beware: It can remove the padding / margin and add a background color to the compose a reply window. */
        html,
        body {
            margin: 0 !important;
            padding: 0 !important;
            height: 100% !important;
            width: 100% !important;
        }

        /* What it does: Stops email clients resizing small text. */
        * {
            -ms-text-size-adjust: 100%;
            -webkit-text-size-adjust: 100%;
        }

        /* What it does: Centers email on Android 4.4 */
        div[style*="margin: 16px 0"] {
            margin: 0 !important;
        }

        /* What it does: Stops Outlook from adding extra spacing to tables. */
        table,
        td {
            mso-table-lspace: 0pt !important;
            mso-table-rspace: 0pt !important;
        }

        /* What it does: Fixes webkit padding issue. */
        table {
            border-spacing: 0 !important;
            border-collapse: collapse !important;
            table-layout: fixed !important;
            margin: 0 auto !important;
        }

        /* What it does: Uses a better rendering method when resizing images in IE. */
        img {
            -ms-interpolation-mode:bicubic;
        }

        /* What it does: Prevents Windows 10 Mail from underlining links despite inline CSS. Styles for underlined links should be inline. */
        a {
            text-decoration: none;
        }

        /* What it does: A work-around for email clients meddling in triggered links. */
        a[x-apple-data-detectors],  /* iOS */
        .unstyle-auto-detected-links a,
        .aBn {
            border-bottom: 0 !important;
            cursor: default !important;
            color: inherit !important;
            text-decoration: none !important;
            font-size: inherit !important;
            font-family: inherit !important;
            font-weight: inherit !important;
            line-height: inherit !important;
        }

        /* What it does: Prevents Gmail from changing the text color in conversation threads. */
        .im {
            color: inherit !important;
        }

        /* What it does: Prevents Gmail from displaying a download button on large, non-linked images. */
        .a6S {
            display: none !important;
            opacity: 0.01 !important;
        }
        /* If the above doesn't work, add a .g-img class to any image in question. */
        img.g-img + div {
            display: none !important;
        }

        /* What it does: Removes right gutter in Gmail iOS app: https://github.com/TedGoas/Cerberus/issues/89  */
        /* Create one of these media queries for each additional viewport size you'd like to fix */

        /* iPhone 4, 4S, 5, 5S, 5C, and 5SE */
        @media only screen and (min-device-width: 320px) and (max-device-width: 374px) {
            u ~ div .email-container {
                min-width: 320px !important;
            }
        }
        /* iPhone 6, 6S, 7, 8, and X */
        @media only screen and (min-device-width: 375px) and (max-device-width: 413px) {
            u ~ div .email-container {
                min-width: 375px !important;
            }
        }
        /* iPhone 6+, 7+, and 8+ */
        @media only screen and (min-device-width: 414px) {
            u ~ div .email-container {
                min-width: 414px !important;
            }
        }

    </style>

    <style>
      h1 {
        margin: 0 0 10px;
         font-size: 25px;
         line-height: 30px;
         color: #333333;
         font-weight: normal;
      }

      h2 {
        margin: 0 0 10px 0;
         font-family: sans-serif;
         font-size: 18px;
         line-height: 22px;
         color: #333333;
         font-weight: bold;
      }

      p {
        margin: 0 0 10px;
      }

      p strong {
        color: #333333;
      }

      ul {
        padding: 0;
         margin: 0;
         list-style-type: disc;
      }

      li {
        margin:0 0 10px 30px;
      }

      .button {
        background: #222222;
         border: 1px solid #000000;
         font-family: sans-serif;
         font-size: 15px;
         line-height: 15px;
         text-decoration: none;
         padding: 13px 17px;
         color: #ffffff;
         display: block;
         border-radius: 4px;
      }
    </style>

    <!-- What it does: Makes background images in 72ppi Outlook render at correct size. -->
    <!--[if gte mso 9]>
    <xml>
        <o:OfficeDocumentSettings>
            <o:AllowPNG/>
            <o:PixelsPerInch>96</o:PixelsPerInch>
        </o:OfficeDocumentSettings>
    </xml>
    <![endif]-->

    <!-- CSS Reset : END -->

    <!-- Progressive Enhancements : BEGIN -->
    <style>

	    /* What it does: Hover styles for buttons */
	    .button-td,
	    .button {
	        transition: all 100ms ease-in;
	    }
	    .button-td:hover,
	    .button:hover {
	        background: #555555 !important;
	        border-color: #555555 !important;
	    }

	    /* Media Queries */
	    @media screen and (max-width: 480px) {

	        /* What it does: Forces table cells into full-width rows. */
	        .stack-column,
	        .stack-column-center {
	            display: block !important;
	            width: 100% !important;
	            max-width: 100% !important;
	            direction: ltr !important;
	        }
	        /* And center justify these ones. */
	        .stack-column-center {
	            text-align: center !important;
	        }

	        /* What it does: Generic utility class for centering. Useful for images, buttons, and nested tables. */
	        .center-on-narrow {
	            text-align: center !important;
	            display: block !important;
	            margin-left: auto !important;
	            margin-right: auto !important;
	            float: none !important;
	        }
	        table.center-on-narrow {
	            display: inline-block !important;
	        }

	        /* What it does: Adjust typography on small screens to improve readability */
	        .email-container p {
	            font-size: 17px !important;
	        }
	    }

    </style>
    <!-- Progressive Enhancements : END -->

</head>
<!--
	The email background color (#222222) is defined in three places:
	1. body tag: for most email clients
	2. center tag: for Gmail and Inbox mobile apps and web versions of Gmail, GSuite, Inbox, Yahoo, AOL, Libero, Comcast, freenet, Mail.ru, Orange.fr
	3. mso conditional: For Windows 10 Mail
-->
<body width="100%" style="margin: 0; padding: 0 !important; mso-line-height-rule: exactly; background-color: #777777;">
	<center style="width: 100%; background-color: #777777;">
    <!--[if mso | IE]>
    <table role="presentation" border="0" cellpadding="0" cellspacing="0" width="100%" style="background-color: #777777;">
    <tr>
    <td>
    <![endif]-->

        <!--
            Set the email width. Defined in two places:
            1. max-width for all clients except Desktop Windows Outlook, allowing the email to squish on narrow but never go wider than 680px.
            2. MSO tags for Desktop Windows Outlook enforce a 680px width.
            Note: The Fluid and Responsive templates have a different width (600px). The hybrid grid is more "fragile", and I've found that 680px is a good width. Change with caution.
        -->
        <div style="max-width: 680px; margin: 0 auto;" class="email-container">
            <!--[if mso]>
            <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" width="680">
            <tr>
            <td>
            <![endif]-->

	        <!-- Email Body : BEGIN -->
	        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="margin: auto;">
		        <!-- Email Header : BEGIN -->
	            <tr>
	                <td style="padding: 25px 0 20px; text-align: center">
                          <% if HackathonConfig['logo_asset'].present? %>
                            <%= image_tag HackathonConfig['logo_asset'], height: "100", alt: "#{HackathonConfig['name']} logo", style: "height: 100px; font-family: sans-serif; font-size: 15px; line-height: 15px; color: #555555;" %>
                          <% else %>
                            <span style="font-size: 24px; color: #fff; font-family: sans-serif; font-weight: bold;"><%= HackathonConfig['name'] %></span>
                          <% end %>
	                </td>
	            </tr>
		        <!-- Email Header : END -->

	            <!-- Hero Image, Flush : BEGIN -->
                <%# <tr>
                    <td style="background-color: #ffffff;">
                        <img src="https://via.placeholder.com/1360x600" width="680" height="" alt="alt_text" border="0" style="width: 100%; max-width: 680px; height: auto; background: #dddddd; font-family: sans-serif; font-size: 15px; line-height: 15px; color: #555555; margin: auto; display: block;" class="g-img">
                    </td>
                </tr> %>
                <!-- Hero Image, Flush : END -->

                <!-- 1 Column Text + Button : BEGIN -->
                <tr>
                    <td style="background-color: #ffffff;">
                        <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%">
                            <tr>
                                <td style="padding: 20px; font-family: sans-serif; font-size: 15px; line-height: 20px; color: #555555;">
                                    <%= yield %>
                                </td>
                            </tr>
                            <tr>
                                <td style="padding: 0 20px 20px;">
                                    <!-- Button : BEGIN -->
                                    <table align="center" role="presentation" cellspacing="0" cellpadding="0" border="0" style="margin: auto;">
                                        <tr>
                                            <td class="button-td" style="border-radius: 4px; background: #222222;">
                                                <a class="button" href="<%= manage_root_url %>">Open Dashboard &raquo;</a>
                                            </td>
                                        </tr>
                                    </table>
                                    <!-- Button : END -->
                                </td>
                            </tr>

                        </table>
                    </td>
                </tr>
                <!-- 1 Column Text + Button : END -->

                <!-- Clear Spacer : BEGIN -->
                <tr>
                    <td aria-hidden="true" height="40" style="font-size: 0px; line-height: 0px;">
                        &nbsp;
                    </td>
                </tr>
                <!-- Clear Spacer : END -->

            </table>
            <!-- Email Body : END -->

            <!-- Email Footer : BEGIN -->
            <%# <table role="presentation" cellspacing="0" cellpadding="0" border="0" width="100%" style="max-width: 680px;">
                <tr>
                    <td style="padding: 20px; font-family: sans-serif; font-size: 12px; line-height: 15px; text-align: center; color: #888888;">
                        Company Name<br><span class="unstyle-auto-detected-links">123 Fake Street, SpringField, OR, 97477 US<br>(123) 456-7890</span>
                        <br><br>
                        <unsubscribe style="color: #888888; text-decoration: underline;">unsubscribe</unsubscribe>
                    </td>
                </tr>
            </table> %>
            <!-- Email Footer : END -->

            <!--[if mso]>
            </td>
            </tr>
            </table>
            <![endif]-->
        </div>

    <!--[if mso | IE]>
    </td>
    </tr>
    </table>
    <![endif]-->
    </center>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= yield(:title) || HackathonConfig['default_page_title'] %>
    </title>
    <meta charset="utf-8"/>
    <meta content="width=device-width, initial-scale=1" name="viewport"/>
    <% if HackathonConfig['favicon_asset'].present? %>
      <link href="<%= image_url(HackathonConfig['favicon_asset']) %>" rel="shortcut icon"></link>
    <% end %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= javascript_include_tag "application", 'data-turbolinks-track': 'reload' %>
    <link href="//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700" rel="stylesheet" type="text/css"></link>
    <% if HackathonConfig['custom_css'].present? %>
      <style>
        <%= HackathonConfig['custom_css'] %>
      </style>
    <% end %>
  </head>
  <body>
    <%= render "layouts/header" %>
    <%= render "layouts/account_nav" %>
    <%= render "layouts/flashes" %>
    <div id="main">
      <section class="section">
        <div class="container">
          <%= yield %>
        </div>
      </section>
    </div>
    <% if cookies[:theming_editor] %>
      <%= render "layouts/theming_editor" %>
    <% end %>
  </body>
</html>

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title= yield(:title) || HackathonConfig.default_page_title
    %meta{ charset: "utf-8" }
    %meta{ name:"viewport", content: "width=device-width, initial-scale=1" }

    - if HackathonConfig.favicon_asset.present?
      %link{ href: image_url(HackathonConfigfavicon_asset), rel: "shortcut icon" }

    = csrf_meta_tags
    = csp_meta_tag

    = stylesheet_link_tag "application", media: "all", 'data-turbo-track': 'reload'
    = javascript_include_tag "application.assets", 'data-turbo-track': 'reload'
    = javascript_importmap_tags

    %link{ href:'//fonts.googleapis.com/css?family=Open+Sans:300,400,600,700', rel: 'stylesheet', type: 'text/css' }
    - if HackathonConfig.custom_css.present?
      %style
        = HackathonConfig.custom_css

  %body
    = render "layouts/header"
    = render "layouts/account_nav"
    = render "layouts/flashes"
    #main
      %section.section
        .container
          = yield
    - if cookies[:theming_editor]
      = render "layouts/theming_editor"

app/views/layouts/hackathon_manager.html.haml
!!! 5
%html
  %head
    %title= yield(:title) || Rails.configuration.hackathon['default_page_title']
    %meta{ charset: "utf-8" }
    %meta{ name:"viewport", content: "width=device-width, initial-scale=1" }
    = stylesheet_link_tag "hackathon_manager/core", media: "all"
    = csrf_meta_tags

  %body
    = render "layouts/header"
    #main
      = yield
    = render "layouts/footer"
    = javascript_include_tag "hackathon_manager/application"
    = render "layouts/shared_footer"

app/views/layouts/user_mailer.html.erb
<%
  context = { message_body: yield }
  message_variables = MessageVariables.new(context)
  message_variables.template = MessageTemplate.instance.html
%>
<%= message_variables.render.html_safe %>